"""initial schema

Revision ID: ba352aa05e2d
Revises: 
Create Date: 2026-03-20 12:19:47.043967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba352aa05e2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_weight_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('body_region', sa.String(length=50), nullable=False),
    sa.Column('is_unilateral', sa.Boolean(), nullable=False),
    sa.Column('is_assisted', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technique_cues', sa.Text(), nullable=True),
    sa.Column('primary_muscles', sa.String(length=255), nullable=True),
    sa.Column('secondary_muscles', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('arm_span_cm', sa.Float(), nullable=True),
    sa.Column('leg_length_cm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('planned_exercises', sa.Text(), nullable=False),
    sa.Column('auto_progression', sa.Boolean(), nullable=False),
    sa.Column('min_technique_score', sa.Float(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_plan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_volume_kg', sa.Float(), nullable=False),
    sa.Column('total_sets', sa.Integer(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('planned_reps', sa.Integer(), nullable=True),
    sa.Column('planned_weight_kg', sa.Float(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_weight_kg', sa.Float(), nullable=True),
    sa.Column('reps_left', sa.Integer(), nullable=True),
    sa.Column('reps_right', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_sets')
    op.drop_table('workout_sessions')
    op.drop_table('workout_plans')
    op.drop_table('users')
    op.drop_table('exercises')
    op.drop_table('body_weight_entries')
    # ### end Alembic commands ###
