#!/usr/bin/env python3
"""
Mega exercise update script:
1. Patches secondary muscles on all existing exercises
2. Adds ~200 missing exercises (bar variants, machines, kettlebell, landmine, etc.)
"""

import json
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "homegym.db"

# ---------------------------------------------------------------------------
# 1. SECONDARY MUSCLE PATCHES  (name -> list of secondary muscles)
# ---------------------------------------------------------------------------
SECONDARY_PATCHES = {
    # ── CHEST FLIES / ISOLATION ──────────────────────────────────────────────
    "cable_chest_fly":          ["front_delts"],
    "cable_crossover":          ["front_delts"],
    "high_cable_crossover":     ["front_delts"],
    "low_cable_crossover":      ["front_delts"],
    "high_to_low_cable_fly":    ["front_delts"],
    "low_to_high_cable_fly":    ["front_delts"],
    "decline_cable_fly":        ["front_delts"],
    "pec_deck":                 ["front_delts"],
    "dumbbell_flye":            ["front_delts"],
    "incline_dumbbell_flye":    ["front_delts"],
    "svend_press":              ["front_delts"],
    "cable_pullover":           ["chest", "teres_major"],
    "machine_pullover":         ["chest", "teres_major"],
    "straight_arm_pulldown":    ["teres_major", "chest"],
    "dumbbell_pullover":        ["teres_major", "chest"],
    "machine_dip":              ["front_delts"],

    # ── REAR DELT / FACE PULLS ───────────────────────────────────────────────
    "cable_face_pull":          ["rear_delts", "rhomboids", "mid_traps"],
    "face_pull":                ["rear_delts", "rhomboids", "mid_traps"],
    "band_pull_apart":          ["rear_delts", "rhomboids"],
    "cable_rear_delt_flye":     ["rhomboids", "mid_traps"],
    "rear_delt_flye":           ["rhomboids", "mid_traps"],
    "rear_delt_fly_dumbbell_supinated": ["rhomboids", "mid_traps"],
    "machine_reverse_flye":     ["rhomboids", "mid_traps"],
    "reverse_pec_deck":         ["rhomboids", "mid_traps"],
    "cable_y_raise":            ["rhomboids", "mid_traps"],
    "prone_y_raise":            ["rhomboids", "mid_traps"],
    "w_raise":                  ["rear_delts", "rhomboids"],
    "chest_supported_prime_machine_row": ["biceps", "teres_major"],

    # ── LATERAL RAISES ───────────────────────────────────────────────────────
    "cable_lateral_raise":      ["upper_traps"],
    "dumbbell_lateral_raise":   ["upper_traps"],
    "machine_lateral_raise":    ["upper_traps"],
    "landmine_lateral_raise":   ["upper_traps"],
    "lateral_raise_cable_false":["upper_traps"],
    "leaning_cable_lateral_raise": ["upper_traps"],
    "lying_cable_lateral_raise": ["upper_traps"],

    # ── FRONT RAISES ─────────────────────────────────────────────────────────
    "cable_front_raise":        ["upper_chest", "upper_traps"],
    "dumbbell_front_raise":     ["upper_chest", "upper_traps"],
    "plate_front_raise":        ["upper_chest", "upper_traps"],

    # ── SHRUGS ───────────────────────────────────────────────────────────────
    "barbell_shrug":            ["upper_back", "neck"],
    "dumbbell_shrug":           ["upper_back", "neck"],
    "cable_shrug":              ["upper_back", "neck"],
    "behind_back_shrug":        ["upper_back", "neck"],
    "smith_machine_shrug":      ["upper_back", "neck"],
    "snatch_grip_shrug":        ["upper_back", "neck"],
    "trap_bar_shrug":           ["upper_back", "neck"],

    # ── BICEP CURLS ──────────────────────────────────────────────────────────
    "barbell_curl":             ["forearms", "brachialis"],
    "bicep_curl_barbell_supinated": ["forearms", "brachialis"],
    "dumbbell_curl":            ["forearms", "brachialis"],
    "cable_curl":               ["forearms", "brachialis"],
    "high_cable_curl":          ["forearms", "brachialis"],
    "hammer_curl":              ["brachialis", "forearms"],
    "cable_hammer_curl":        ["brachialis", "forearms"],
    "cross_body_hammer_curl":   ["brachialis", "forearms"],
    "ez_bar_curl":              ["forearms", "brachialis"],
    "rackable_ez_bar_curl":     ["forearms", "brachialis"],
    "swiss_bar_curl":           ["forearms", "brachialis"],
    "axle_bar_curl":            ["brachialis"],
    "preacher_curl":            ["brachialis"],
    "ez_bar_preacher_curl":     ["brachialis"],
    "machine_preacher_curl":    ["brachialis"],
    "single_arm_preacher_curl": ["brachialis"],
    "machine_curl":             ["brachialis"],
    "concentration_curl":       ["brachialis"],
    "spider_curl":              ["brachialis"],
    "ez_bar_spider_curl":       ["brachialis"],
    "incline_curl":             ["brachialis"],
    "drag_curl":                ["brachialis", "rear_delts"],
    "bayesian_curl":            ["brachialis"],
    "reverse_curl":             ["brachialis"],
    "reverse_ez_bar_curl":      ["brachialis"],
    "ez_bar_reverse_curl":      ["brachialis"],
    "zottman_curl":             ["brachialis"],

    # ── TRICEP ISOLATION ─────────────────────────────────────────────────────
    "skull_crusher":            ["forearms"],
    "ez_bar_skull_crusher":     ["forearms"],
    "swiss_bar_skull_crusher":  ["forearms"],
    "cable_skull_crusher":      ["forearms"],
    "rackable_ez_bar_skull_crusher_forehead": ["forearms"],
    "lying_tricep_extension":   ["forearms"],
    "overhead_tricep_extension":["forearms"],
    "cable_overhead_extension": ["forearms"],
    "single_arm_overhead_extension": ["forearms"],
    "ez_bar_overhead_extension":["forearms"],
    "rolling_tricep_extension": ["forearms"],
    "french_press":             ["forearms"],
    "tate_press":               ["forearms", "chest"],
    "rope_pushdown":            ["forearms"],
    "bar_pushdown":             ["forearms"],
    "single_arm_pushdown":      ["forearms"],
    "cable_kickback":           ["forearms"],
    "kickback":                 ["forearms"],
    "tricep_pushdown":          ["forearms"],
    "tricep_pushdown_bands_pronated": ["forearms"],

    # ── BACK ISOLATION ───────────────────────────────────────────────────────
    "back_extension":           ["hamstrings", "glutes", "erectors"],
    "reverse_hyperextension":   ["lower_back", "hamstrings"],
    "reverse_hyper":            ["lower_back", "erectors"],

    # ── CORE ─────────────────────────────────────────────────────────────────
    "ab_wheel":                 ["hip_flexors", "shoulders", "lats"],
    "cable_crunch":             ["hip_flexors"],
    "machine_crunch":           ["hip_flexors"],
    "hanging_leg_raise":        ["hip_flexors", "lats"],
    "lying_leg_raise":          ["hip_flexors"],
    "toes_to_bar":              ["hip_flexors", "lats"],
    "dragon_flag":              ["hip_flexors", "chest"],
    "dead_bug":                 ["hip_flexors"],
    "bird_dog":                 ["glutes", "erectors"],
    "russian_twist":            ["hip_flexors"],
    "reverse_crunch":           ["hip_flexors"],
    "plank":                    ["shoulders", "glutes"],
    "side_plank":               ["hip_abductors"],
    "pallof_press":             ["shoulders", "hip_flexors"],
    "woodchop":                 ["shoulders", "hip_flexors"],
    "v_up":                     ["hip_flexors"],
    "vacuum":                   ["transverse_abdominis"],

    # ── GLUTES / HIPS ────────────────────────────────────────────────────────
    "cable_glute_kickback":     ["hamstrings"],
    "glute_kickback":           ["hamstrings"],
    "donkey_kick":              ["hamstrings"],
    "clamshell":                ["hip_abductors"],
    "frog_pump":                ["hamstrings"],
    "hip_abduction_machine":    ["glute_med", "tfl"],
    "hip_adduction_machine":    ["inner_thighs"],
    "cable_hip_abduction":      ["glute_med", "tfl"],
    "cable_pull_through":       ["lower_back", "erectors"],
    "belt_squat_rdl":           ["lower_back", "erectors"],

    # ── HAMSTRINGS ───────────────────────────────────────────────────────────
    "leg_curl":                 ["calves", "glutes"],
    "lying_leg_curl":           ["calves", "glutes"],
    "seated_leg_curl":          ["calves", "glutes"],
    "single_leg_curl":          ["calves", "glutes"],
    "leg_curl_machine_false_narrow": ["calves", "glutes"],
    "dumbbell_leg_curl":        ["calves", "glutes"],
    "natural_leg_curl":         ["calves", "glutes"],
    "nordic_curl":              ["calves", "glutes"],
    "glute_ham_raise":          ["calves", "lower_back"],

    # ── QUADS ────────────────────────────────────────────────────────────────
    "leg_extension":            ["hip_flexors"],
    "single_leg_extension":     ["hip_flexors"],
    "leg_extension_machine_false_wide": ["hip_flexors"],
    "terminal_knee_extension":  ["hip_stabilizers"],
    "sissy_squat":              ["hip_flexors"],
    "pistol_squats":            ["glutes", "calves"],

    # ── CALVES ───────────────────────────────────────────────────────────────
    "standing_calf_raise":      ["soleus", "tibialis"],
    "seated_calf_raise":        ["gastrocnemius", "tibialis"],
    "single_leg_calf_raise":    ["soleus", "tibialis"],
    "donkey_calf_raise":        ["soleus"],
    "smith_machine_calf_raise": ["soleus"],
    "leg_press_calf_raise":     ["soleus"],
    "calf_raise_machine_false_wide": ["soleus"],

    # ── GRIP / FOREARM ───────────────────────────────────────────────────────
    "dead_hang":                ["lats", "shoulders", "biceps"],
    "plate_pinch":              ["wrists"],
    "wrist_curl":               ["wrists"],
    "reverse_wrist_curl":       ["wrists"],
    "wrist_roller":             ["wrists"],
    "farmer_carry":             ["core", "traps", "shoulders"],
    "towel_pull_up":            ["back", "biceps"],

    # ── NECK ─────────────────────────────────────────────────────────────────
    "neck_extension":           ["upper_traps"],
    "neck_flexion":             ["sternocleidomastoid"],
    "neck_harness":             ["upper_traps"],
    "neck_lateral_flexion":     ["upper_traps"],
}

# ---------------------------------------------------------------------------
# 2. NEW EXERCISES TO ADD
# ---------------------------------------------------------------------------
# Fields: name, display_name, movement_type, body_region, primary, secondary
NEW_EXERCISES = [

    # ══════════════════════════════════════════════════════════════════════════
    # TRAP BAR / HEX BAR
    # ══════════════════════════════════════════════════════════════════════════
    ("trap_bar_rdl",            "Trap Bar Romanian Deadlift",       "compound","lower",
     ["hamstrings","glutes"],       ["lower_back","traps","forearms"]),
    ("trap_bar_squat",          "Trap Bar Squat",                   "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves","core"]),
    ("trap_bar_hip_thrust",     "Trap Bar Hip Thrust",              "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("trap_bar_walking_lunge",  "Trap Bar Walking Lunge",           "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("trap_bar_split_squat",    "Trap Bar Split Squat",             "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("trap_bar_deadlift_deficit","Trap Bar Deficit Deadlift",       "compound","lower",
     ["hamstrings","glutes","back"],["traps","quadriceps","forearms"]),
    ("trap_bar_bent_over_row",  "Trap Bar Bent Over Row",           "compound","upper",
     ["back","lats"],               ["biceps","rear_delts"]),
    ("trap_bar_curl",           "Trap Bar Curl",                    "isolation","upper",
     ["biceps"],                    ["forearms","brachialis"]),
    ("trap_bar_good_morning",   "Trap Bar Good Morning",            "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),

    # ══════════════════════════════════════════════════════════════════════════
    # CAMBERED BAR
    # ══════════════════════════════════════════════════════════════════════════
    ("cambered_bar_rdl",        "Cambered Bar Romanian Deadlift",   "compound","lower",
     ["hamstrings"],                ["glutes","lower_back","forearms"]),
    ("cambered_bar_incline_press","Cambered Bar Incline Press",     "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("cambered_bar_decline_press","Cambered Bar Decline Press",     "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("cambered_bar_close_grip_bench","Cambered Bar Close Grip Bench","compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("cambered_bar_front_squat","Cambered Bar Front Squat",         "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings","upper_back"]),
    ("cambered_bar_hip_thrust", "Cambered Bar Hip Thrust",          "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("cambered_bar_split_squat","Cambered Bar Split Squat",         "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("cambered_bar_lunge",      "Cambered Bar Lunge",               "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("cambered_bar_floor_press","Cambered Bar Floor Press",         "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),

    # ══════════════════════════════════════════════════════════════════════════
    # SSB (SAFETY SQUAT BAR) ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("ssb_rdl",                 "SSB Romanian Deadlift",            "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("ssb_hip_thrust",          "SSB Hip Thrust",                   "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("ssb_split_squat",         "SSB Split Squat",                  "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("ssb_deadlift",            "SSB Deadlift",                     "compound","lower",
     ["hamstrings","glutes","back"],["traps","quadriceps"]),
    ("ssb_zercher_squat",       "SSB Zercher Squat",                "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","biceps","upper_back"]),
    ("ssb_deficit_squat",       "SSB Deficit Squat",                "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),
    ("ssb_heel_elevated_squat", "SSB Heel Elevated Squat",          "compound","lower",
     ["quadriceps"],                ["glutes","calves"]),
    ("ssb_high_bar_squat",      "SSB High Bar Squat",               "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),
    ("ssb_wide_squat",          "SSB Wide Stance Squat",            "compound","lower",
     ["glutes","quadriceps"],       ["hamstrings","adductors"]),

    # ══════════════════════════════════════════════════════════════════════════
    # BUFFALO BAR
    # ══════════════════════════════════════════════════════════════════════════
    ("buffalo_bar_rdl",         "Buffalo Bar Romanian Deadlift",    "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("buffalo_bar_deadlift",    "Buffalo Bar Deadlift",             "compound","lower",
     ["hamstrings","glutes","back"],["traps","quadriceps"]),
    ("buffalo_bar_row",         "Buffalo Bar Row",                  "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("buffalo_bar_overhead_press","Buffalo Bar Overhead Press",     "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest","core"]),
    ("buffalo_bar_front_squat", "Buffalo Bar Front Squat",          "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings","upper_back"]),
    ("buffalo_bar_close_grip_bench","Buffalo Bar Close Grip Bench", "compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("buffalo_bar_incline_press","Buffalo Bar Incline Press",       "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("buffalo_bar_floor_press", "Buffalo Bar Floor Press",          "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("buffalo_bar_hip_thrust",  "Buffalo Bar Hip Thrust",           "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),

    # ══════════════════════════════════════════════════════════════════════════
    # DUFFALO BAR
    # ══════════════════════════════════════════════════════════════════════════
    ("duffalo_bar_overhead_press","Duffalo Bar Overhead Press",     "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest","core"]),
    ("duffalo_bar_row",         "Duffalo Bar Row",                  "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("duffalo_bar_rdl",         "Duffalo Bar Romanian Deadlift",    "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("duffalo_bar_front_squat", "Duffalo Bar Front Squat",          "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings","upper_back"]),
    ("duffalo_bar_incline_press","Duffalo Bar Incline Press",       "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("duffalo_bar_close_grip_bench","Duffalo Bar Close Grip Bench", "compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("duffalo_bar_floor_press", "Duffalo Bar Floor Press",          "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("duffalo_bar_hip_thrust",  "Duffalo Bar Hip Thrust",           "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),

    # ══════════════════════════════════════════════════════════════════════════
    # SWISS BAR (MULTI-GRIP / FOOTBALL BAR)
    # ══════════════════════════════════════════════════════════════════════════
    ("swiss_bar_rdl",           "Swiss Bar Romanian Deadlift",      "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("swiss_bar_hip_thrust",    "Swiss Bar Hip Thrust",             "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("swiss_bar_close_grip_bench","Swiss Bar Close Grip Bench",     "compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("swiss_bar_floor_press",   "Swiss Bar Floor Press",            "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("swiss_bar_shrug",         "Swiss Bar Shrug",                  "isolation","upper",
     ["traps"],                     ["upper_back","neck"]),
    ("swiss_bar_upright_row",   "Swiss Bar Upright Row",            "compound","upper",
     ["shoulders","traps"],         ["biceps"]),
    ("swiss_bar_deadlift",      "Swiss Bar Deadlift",               "compound","lower",
     ["hamstrings","glutes","back"],["traps","quadriceps"]),
    ("swiss_bar_good_morning",  "Swiss Bar Good Morning",           "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),
    ("swiss_bar_split_squat",   "Swiss Bar Split Squat",            "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("swiss_bar_incline_close_grip","Swiss Bar Incline Close Grip", "compound","upper",
     ["chest","triceps"],           ["front_delts"]),
    ("swiss_bar_decline_press", "Swiss Bar Decline Press",          "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),

    # ══════════════════════════════════════════════════════════════════════════
    # AXLE BAR
    # ══════════════════════════════════════════════════════════════════════════
    ("axle_bar_squat",          "Axle Bar Squat",                   "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves","core"]),
    ("axle_bar_rdl",            "Axle Bar Romanian Deadlift",       "compound","lower",
     ["hamstrings"],                ["glutes","lower_back","forearms"]),
    ("axle_bar_hip_thrust",     "Axle Bar Hip Thrust",              "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("axle_bar_close_grip_bench","Axle Bar Close Grip Bench",       "compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("axle_bar_floor_press",    "Axle Bar Floor Press",             "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("axle_bar_incline_press",  "Axle Bar Incline Press",           "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("axle_bar_front_squat",    "Axle Bar Front Squat",             "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings","upper_back"]),
    ("axle_bar_good_morning",   "Axle Bar Good Morning",            "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),
    ("axle_bar_shrug",          "Axle Bar Shrug",                   "isolation","upper",
     ["traps"],                     ["upper_back","neck","forearms"]),
    ("axle_bar_upright_row",    "Axle Bar Upright Row",             "compound","upper",
     ["shoulders","traps"],         ["biceps","forearms"]),
    ("axle_bar_skull_crusher",  "Axle Bar Skull Crusher",           "isolation","upper",
     ["triceps"],                   ["forearms"]),
    ("axle_bar_press",          "Axle Bar Press (Flat)",            "compound","upper",
     ["chest"],                     ["triceps","front_delts","forearms"]),
    ("axle_bar_zercher_squat",  "Axle Bar Zercher Squat",           "compound","lower",
     ["quadriceps","glutes"],       ["biceps","upper_back","hamstrings"]),

    # ══════════════════════════════════════════════════════════════════════════
    # EZ BAR ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("ez_bar_close_grip_bench", "EZ Bar Close Grip Bench",          "compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("ez_bar_floor_press",      "EZ Bar Floor Press",               "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("ez_bar_rdl",              "EZ Bar Romanian Deadlift",         "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("ez_bar_hip_thrust",       "EZ Bar Hip Thrust",                "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("ez_bar_shrug",            "EZ Bar Shrug",                     "isolation","upper",
     ["traps"],                     ["upper_back","neck"]),
    ("ez_bar_decline_press",    "EZ Bar Decline Press",             "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("ez_bar_incline_skull_crusher","EZ Bar Incline Skull Crusher", "isolation","upper",
     ["triceps"],                   ["forearms"]),
    ("ez_bar_tate_press",       "EZ Bar Tate Press",                "isolation","upper",
     ["triceps"],                   ["forearms","chest"]),
    ("ez_bar_drag_curl",        "EZ Bar Drag Curl",                 "isolation","upper",
     ["biceps"],                    ["brachialis","rear_delts"]),

    # ══════════════════════════════════════════════════════════════════════════
    # RACKABLE EZ BAR ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("rackable_ez_bar_overhead_press","Rackable EZ Bar Overhead Press","compound","upper",
     ["shoulders"],                 ["triceps","upper_chest","core"]),
    ("rackable_ez_bar_row",     "Rackable EZ Bar Row",              "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("rackable_ez_bar_incline_press","Rackable EZ Bar Incline Press","compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("rackable_ez_bar_rdl",     "Rackable EZ Bar Romanian Deadlift","compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("rackable_ez_bar_good_morning","Rackable EZ Bar Good Morning", "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),
    ("rackable_ez_bar_upright_row","Rackable EZ Bar Upright Row",  "compound","upper",
     ["shoulders","traps"],         ["biceps"]),
    ("rackable_ez_bar_close_grip_bench","Rackable EZ Bar Close Grip Bench","compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("rackable_ez_bar_floor_press","Rackable EZ Bar Floor Press",  "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("rackable_ez_bar_hip_thrust","Rackable EZ Bar Hip Thrust",    "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("rackable_ez_bar_decline_press","Rackable EZ Bar Decline Press","compound","upper",
     ["chest"],                     ["triceps","front_delts"]),

    # ══════════════════════════════════════════════════════════════════════════
    # LOG BAR
    # ══════════════════════════════════════════════════════════════════════════
    ("log_strict_press",        "Log Strict Press",                 "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest","core"]),
    ("log_push_press",          "Log Push Press",                   "compound","full_body",
     ["shoulders","quadriceps"],    ["triceps","core","glutes"]),
    ("log_clean",               "Log Clean",                        "compound","full_body",
     ["quadriceps","glutes","back"],["traps","shoulders","forearms"]),
    ("log_deadlift",            "Log Deadlift",                     "compound","lower",
     ["hamstrings","glutes","back"],["traps","forearms"]),
    ("log_floor_press",         "Log Floor Press",                  "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("log_bent_over_row",       "Log Bent Over Row",                "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),

    # ══════════════════════════════════════════════════════════════════════════
    # HAMMER STRENGTH MACHINES
    # ══════════════════════════════════════════════════════════════════════════
    ("hammer_strength_decline_press","Hammer Strength Decline Press","compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("hammer_strength_shoulder_press","Hammer Strength Shoulder Press","compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("hammer_strength_overhead_press","Hammer Strength Overhead Press","compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("hammer_strength_high_row","Hammer Strength High Row",         "compound","upper",
     ["upper_back","lats"],         ["biceps","rear_delts"]),
    ("hammer_strength_low_row", "Hammer Strength Low Row",          "compound","upper",
     ["lats","mid_back"],           ["biceps","teres_major"]),
    ("hammer_strength_lat_pulldown","Hammer Strength Lat Pulldown", "compound","upper",
     ["lats"],                      ["biceps","teres_major"]),
    ("hammer_strength_wide_chest_press","Hammer Strength Wide Chest Press","compound","upper",
     ["chest"],                     ["front_delts","triceps"]),
    ("hammer_strength_pull_down","Hammer Strength Pull-Down",       "compound","upper",
     ["lats"],                      ["biceps","teres_major"]),
    ("hammer_strength_seated_dip","Hammer Strength Seated Dip",    "compound","upper",
     ["triceps","chest"],           ["front_delts"]),
    ("hammer_strength_bicep_curl","Hammer Strength Bicep Curl",    "isolation","upper",
     ["biceps"],                    ["brachialis","forearms"]),
    ("hammer_strength_tricep_dip","Hammer Strength Tricep Dip",    "compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("hammer_strength_leg_press","Hammer Strength Leg Press",       "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("hammer_strength_leg_curl","Hammer Strength Leg Curl",         "isolation","lower",
     ["hamstrings"],                ["calves","glutes"]),
    ("hammer_strength_leg_extension","Hammer Strength Leg Extension","isolation","lower",
     ["quadriceps"],                ["hip_flexors"]),
    ("hammer_strength_calf_raise","Hammer Strength Calf Raise",    "isolation","lower",
     ["calves"],                    ["soleus"]),
    ("hammer_strength_glute_drive","Hammer Strength Glute Drive",  "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),

    # ══════════════════════════════════════════════════════════════════════════
    # ISO-LATERAL MACHINES (plate-loaded)
    # ══════════════════════════════════════════════════════════════════════════
    ("iso_lateral_chest_press", "Iso-Lateral Chest Press",          "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("iso_lateral_incline_press","Iso-Lateral Incline Press",       "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("iso_lateral_decline_press","Iso-Lateral Decline Press",       "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("iso_lateral_shoulder_press","Iso-Lateral Shoulder Press",     "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("iso_lateral_lat_pulldown","Iso-Lateral Lat Pulldown",         "compound","upper",
     ["lats"],                      ["biceps","teres_major"]),
    ("iso_lateral_high_row",    "Iso-Lateral High Row",             "compound","upper",
     ["upper_back","lats"],         ["biceps","rear_delts"]),
    ("iso_lateral_low_row",     "Iso-Lateral Low Row",              "compound","upper",
     ["lats","mid_back"],           ["biceps","teres_major"]),
    ("iso_lateral_front_pulldown","Iso-Lateral Front Pulldown",     "compound","upper",
     ["lats"],                      ["biceps","rear_delts"]),
    ("iso_lateral_wide_pulldown","Iso-Lateral Wide Pulldown",       "compound","upper",
     ["lats","teres_major"],        ["biceps","rear_delts"]),
    ("iso_lateral_leg_press",   "Iso-Lateral Leg Press",            "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("iso_lateral_squat",       "Iso-Lateral Hack Squat Machine",   "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),

    # ══════════════════════════════════════════════════════════════════════════
    # OTHER PLATE-LOADED MACHINES
    # ══════════════════════════════════════════════════════════════════════════
    ("plate_loaded_chest_press","Plate-Loaded Chest Press",         "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("plate_loaded_incline_press","Plate-Loaded Incline Press",     "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("plate_loaded_decline_press","Plate-Loaded Decline Press",     "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("plate_loaded_lat_pulldown","Plate-Loaded Lat Pulldown",       "compound","upper",
     ["lats"],                      ["biceps","teres_major"]),
    ("plate_loaded_row",        "Plate-Loaded Row",                 "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("plate_loaded_shoulder_press","Plate-Loaded Shoulder Press",   "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("plate_loaded_leg_press",  "Plate-Loaded Leg Press",           "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("plate_loaded_hip_thrust", "Plate-Loaded Hip Thrust Machine",  "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("plate_loaded_calf_raise", "Plate-Loaded Calf Raise",          "isolation","lower",
     ["calves"],                    ["soleus"]),
    ("plate_loaded_seated_row", "Plate-Loaded Seated Row",          "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),

    # ══════════════════════════════════════════════════════════════════════════
    # LEG PRESS VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("leg_press_45_degree",     "45-Degree Leg Press",              "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("leg_press_vertical",      "Vertical Leg Press",               "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("leg_press_high_foot",     "Leg Press High Foot Placement",    "compound","lower",
     ["glutes","hamstrings"],       ["quadriceps"]),
    ("leg_press_low_foot",      "Leg Press Low Foot Placement",     "compound","lower",
     ["quadriceps"],                ["glutes"]),
    ("leg_press_wide_stance",   "Leg Press Wide Stance",            "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("leg_press_narrow_stance", "Leg Press Narrow Stance",          "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),
    ("leg_press_single_leg_calf","Leg Press Single Leg Calf Raise", "isolation","lower",
     ["calves"],                    ["soleus"]),
    ("v_squat_machine",         "V-Squat Machine",                  "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),

    # ══════════════════════════════════════════════════════════════════════════
    # HACK SQUAT MACHINE VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("hack_squat_narrow",       "Hack Squat Narrow Stance",         "compound","lower",
     ["quadriceps"],                ["glutes","calves"]),
    ("hack_squat_wide",         "Hack Squat Wide Stance",           "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("hack_squat_heel_elevated","Hack Squat Heels Elevated",        "compound","lower",
     ["quadriceps"],                ["glutes","calves"]),
    ("hack_squat_single_leg",   "Single Leg Hack Squat",            "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),

    # ══════════════════════════════════════════════════════════════════════════
    # OTHER MACHINES
    # ══════════════════════════════════════════════════════════════════════════
    ("machine_standing_leg_curl","Machine Standing Leg Curl",       "isolation","lower",
     ["hamstrings"],                ["calves","glutes"]),
    ("machine_hip_thrust",      "Hip Thrust Machine",               "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("glute_ham_developer",     "Glute Ham Developer (GHD)",        "compound","lower",
     ["hamstrings","glutes"],       ["calves","lower_back"]),
    ("rotary_torso_machine",    "Rotary Torso Machine",             "isolation","upper",
     ["obliques"],                  ["core"]),
    ("ab_coaster",              "Ab Coaster",                       "isolation","upper",
     ["abs"],                       ["hip_flexors","obliques"]),
    ("gravitron_pull_up",       "Gravitron Assisted Pull-Up",       "compound","upper",
     ["lats"],                      ["biceps","teres_major"]),
    ("gravitron_dip",           "Gravitron Assisted Dip",           "compound","upper",
     ["triceps","chest"],           ["front_delts"]),
    ("assisted_dip_machine",    "Assisted Dip Machine",             "compound","upper",
     ["triceps","chest"],           ["front_delts"]),
    ("machine_back_extension",  "Machine Back Extension",           "compound","lower",
     ["erectors","lower_back"],     ["glutes","hamstrings"]),
    ("roman_chair_back_extension","Roman Chair Back Extension",     "compound","lower",
     ["erectors","lower_back"],     ["glutes","hamstrings"]),
    ("45_degree_back_extension","45-Degree Back Extension",         "compound","lower",
     ["erectors","lower_back"],     ["glutes","hamstrings"]),
    ("multi_hip_machine",       "Multi-Hip Machine",                "isolation","lower",
     ["glutes","hip_flexors"],      ["hamstrings","hip_abductors"]),
    ("total_hip_machine",       "Total Hip Machine",                "isolation","lower",
     ["glutes","hip_flexors"],      ["hamstrings","hip_abductors"]),
    ("machine_fly",             "Machine Fly (Pec Deck Flat)",      "isolation","upper",
     ["chest"],                     ["front_delts"]),
    ("machine_incline_fly",     "Machine Incline Fly",              "isolation","upper",
     ["chest"],                     ["front_delts"]),
    ("machine_decline_fly",     "Machine Decline Fly",              "isolation","upper",
     ["chest"],                     ["front_delts"]),
    ("machine_decline_press",   "Machine Decline Press",            "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("life_fitness_chest_press","Life Fitness Chest Press",         "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("life_fitness_shoulder_press","Life Fitness Shoulder Press",   "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("life_fitness_lat_pulldown","Life Fitness Lat Pulldown",       "compound","upper",
     ["lats"],                      ["biceps","teres_major"]),
    ("life_fitness_row",        "Life Fitness Seated Row",          "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("life_fitness_leg_press",  "Life Fitness Leg Press",           "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("nautilus_chest_press",    "Nautilus Chest Press",             "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("nautilus_shoulder_press", "Nautilus Shoulder Press",          "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("nautilus_pullover",       "Nautilus Pullover Machine",        "isolation","upper",
     ["lats","teres_major"],        ["chest","triceps"]),
    ("cybex_arc_lateral_raise", "Cybex Arc Lateral Raise Machine",  "isolation","upper",
     ["shoulders"],                 ["upper_traps"]),
    ("cybex_eagle_fly",         "Cybex Eagle Fly",                  "isolation","upper",
     ["chest"],                     ["front_delts"]),
    ("prime_fitness_fly",       "Prime Fitness Fly Machine",        "isolation","upper",
     ["chest"],                     ["front_delts"]),
    ("prime_fitness_row",       "Prime Fitness Row",                "compound","upper",
     ["back","rear_delts"],         ["biceps"]),
    ("diverging_lat_pulldown",  "Diverging Lat Pulldown Machine",   "compound","upper",
     ["lats"],                      ["biceps","teres_major"]),
    ("converging_chest_press",  "Converging Chest Press Machine",   "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("tibia_dorsiflexion_machine","Tibia Dorsiflexion Machine",     "isolation","lower",
     ["tibialis_anterior"],         []),
    ("seated_hip_flexor_machine","Seated Hip Flexor Machine",       "isolation","lower",
     ["hip_flexors"],               ["quadriceps"]),
    ("lying_abductor_machine",  "Lying Abductor Machine",           "isolation","lower",
     ["glute_med","tfl"],           ["hip_abductors"]),

    # ══════════════════════════════════════════════════════════════════════════
    # DUMBBELL ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("dumbbell_rdl",            "Dumbbell Romanian Deadlift",       "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("dumbbell_stiff_leg_deadlift","Dumbbell Stiff Leg Deadlift",  "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("dumbbell_split_squat",    "Dumbbell Split Squat",             "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("dumbbell_sumo_squat",     "Dumbbell Sumo Squat",              "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("dumbbell_hip_thrust",     "Dumbbell Hip Thrust",              "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("dumbbell_decline_press",  "Dumbbell Decline Press",           "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("dumbbell_floor_press",    "Dumbbell Floor Press",             "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("dumbbell_walking_lunge",  "Dumbbell Walking Lunge",           "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("dumbbell_reverse_lunge",  "Dumbbell Reverse Lunge",           "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("dumbbell_curtsy_lunge",   "Dumbbell Curtsy Lunge",            "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("dumbbell_incline_row",    "Dumbbell Incline Row",             "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("dumbbell_glute_bridge",   "Dumbbell Glute Bridge",            "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("dumbbell_single_leg_rdl", "Dumbbell Single Leg RDL",          "compound","lower",
     ["hamstrings","glutes"],       ["lower_back","core"]),
    ("dumbbell_single_leg_hip_thrust","Dumbbell Single Leg Hip Thrust","compound","lower",
     ["glutes"],                    ["hamstrings"]),
    ("dumbbell_step_up",        "Dumbbell Step Up",                 "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("dumbbell_lateral_squat",  "Dumbbell Lateral Squat",           "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("dumbbell_zercher_squat",  "Dumbbell Zercher Squat",           "compound","lower",
     ["quadriceps","glutes"],       ["biceps","upper_back"]),
    ("dumbbell_overhead_squat", "Dumbbell Overhead Squat",          "compound","full_body",
     ["quadriceps"],                ["glutes","shoulders","core"]),
    ("dumbbell_z_press",        "Dumbbell Z-Press",                 "compound","upper",
     ["shoulders"],                 ["triceps","core"]),
    ("dumbbell_skull_crusher",  "Dumbbell Skull Crusher",           "isolation","upper",
     ["triceps"],                   ["forearms"]),
    ("dumbbell_tate_press",     "Dumbbell Tate Press",              "isolation","upper",
     ["triceps"],                   ["forearms","chest"]),
    ("dumbbell_spider_curl",    "Dumbbell Spider Curl",             "isolation","upper",
     ["biceps"],                    ["brachialis"]),
    ("dumbbell_drag_curl",      "Dumbbell Drag Curl",               "isolation","upper",
     ["biceps"],                    ["brachialis","rear_delts"]),
    ("dumbbell_wrist_curl",     "Dumbbell Wrist Curl",              "isolation","upper",
     ["forearms"],                  ["wrists"]),
    ("dumbbell_reverse_wrist_curl","Dumbbell Reverse Wrist Curl",   "isolation","upper",
     ["forearms"],                  ["wrists"]),
    ("dumbbell_lateral_lunge",  "Dumbbell Lateral Lunge",           "compound","lower",
     ["glutes","adductors"],        ["quadriceps"]),
    ("dumbbell_good_morning",   "Dumbbell Good Morning",            "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),

    # ══════════════════════════════════════════════════════════════════════════
    # KETTLEBELL ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("kettlebell_rdl",          "Kettlebell Romanian Deadlift",     "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("kettlebell_sumo_deadlift","Kettlebell Sumo Deadlift",         "compound","lower",
     ["hamstrings","glutes"],       ["adductors","lower_back"]),
    ("kettlebell_hip_thrust",   "Kettlebell Hip Thrust",            "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("kettlebell_clean",        "Kettlebell Clean",                 "compound","full_body",
     ["quadriceps","glutes","back"],["traps","shoulders","forearms"]),
    ("kettlebell_snatch",       "Kettlebell Snatch",                "compound","full_body",
     ["quadriceps","glutes","shoulders"],["traps","back","core"]),
    ("kettlebell_turkish_get_up","Kettlebell Turkish Get-Up",       "compound","full_body",
     ["shoulders","core"],          ["glutes","hip_flexors","triceps"]),
    ("kettlebell_press",        "Kettlebell Press",                 "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest","core"]),
    ("kettlebell_row",          "Kettlebell Row",                   "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("kettlebell_halo",         "Kettlebell Halo",                  "compound","upper",
     ["shoulders","core"],          ["upper_back"]),
    ("kettlebell_windmill",     "Kettlebell Windmill",              "compound","full_body",
     ["core","obliques"],           ["shoulders","hamstrings"]),
    ("kettlebell_single_arm_press","Kettlebell Single Arm Press",   "compound","upper",
     ["shoulders"],                 ["triceps","core","upper_chest"]),
    ("kettlebell_front_squat",  "Kettlebell Front Squat",           "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings","upper_back"]),
    ("kettlebell_split_squat",  "Kettlebell Split Squat",           "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("kettlebell_lunge",        "Kettlebell Lunge",                 "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("kettlebell_lateral_raise","Kettlebell Lateral Raise",         "isolation","upper",
     ["shoulders"],                 ["upper_traps"]),
    ("kettlebell_upright_row",  "Kettlebell Upright Row",           "compound","upper",
     ["shoulders","traps"],         ["biceps"]),
    ("kettlebell_suitcase_carry","Kettlebell Suitcase Carry",       "compound","full_body",
     ["core","obliques"],           ["traps","forearms","glutes"]),
    ("kettlebell_farmer_carry", "Kettlebell Farmer Carry",          "compound","full_body",
     ["forearms","traps"],          ["core","shoulders"]),
    ("kettlebell_bottoms_up_press","Kettlebell Bottoms-Up Press",   "compound","upper",
     ["shoulders"],                 ["triceps","forearms","core"]),
    ("kettlebell_goblet_squat", "Kettlebell Goblet Squat",          "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings","upper_back"]),
    ("kettlebell_deadlift",     "Kettlebell Deadlift",              "compound","lower",
     ["hamstrings","glutes","back"],["traps","forearms"]),
    ("kettlebell_swing_single_arm","Single Arm Kettlebell Swing",   "compound","full_body",
     ["glutes","hamstrings"],       ["back","shoulders","core"]),
    ("kettlebell_overhead_squat","Kettlebell Overhead Squat",       "compound","full_body",
     ["quadriceps"],                ["shoulders","glutes","core"]),
    ("kettlebell_clean_and_press","Kettlebell Clean and Press",     "compound","full_body",
     ["quadriceps","glutes","shoulders"],["traps","back","triceps"]),
    ("double_kettlebell_press", "Double Kettlebell Press",          "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest","core"]),
    ("double_kettlebell_front_squat","Double Kettlebell Front Squat","compound","lower",
     ["quadriceps"],                ["glutes","hamstrings","upper_back"]),
    ("double_kettlebell_row",   "Double Kettlebell Row",            "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),

    # ══════════════════════════════════════════════════════════════════════════
    # LANDMINE ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("landmine_rdl",            "Landmine Romanian Deadlift",       "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("landmine_deadlift",       "Landmine Deadlift",                "compound","lower",
     ["hamstrings","glutes","back"],["traps","quadriceps"]),
    ("landmine_split_squat",    "Landmine Split Squat",             "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("landmine_hip_thrust",     "Landmine Hip Thrust",              "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("landmine_t_bar_row",      "Landmine T-Bar Row",               "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("landmine_goblet_squat",   "Landmine Goblet Squat",            "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings","upper_back"]),
    ("landmine_anti_rotation",  "Landmine Anti-Rotation Press",     "compound","upper",
     ["core","obliques"],           ["shoulders","hip_flexors"]),
    ("landmine_single_arm_row", "Landmine Single Arm Row",          "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("landmine_curl",           "Landmine Curl",                    "isolation","upper",
     ["biceps"],                    ["forearms","brachialis"]),
    ("landmine_tricep_extension","Landmine Tricep Extension",       "isolation","upper",
     ["triceps"],                   ["forearms"]),
    ("landmine_front_raise",    "Landmine Front Raise",             "isolation","upper",
     ["shoulders"],                 ["upper_chest","core"]),
    ("landmine_rotation",       "Landmine Rotation",                "compound","full_body",
     ["obliques","core"],           ["shoulders","hips"]),
    ("landmine_good_morning",   "Landmine Good Morning",            "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),
    ("landmine_chest_press",    "Landmine Chest Press",             "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("landmine_high_pull",      "Landmine High Pull",               "compound","full_body",
     ["traps","shoulders"],         ["back","glutes","hamstrings"]),
    ("landmine_sumo_squat",     "Landmine Sumo Squat",              "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("landmine_reverse_lunge",  "Landmine Reverse Lunge",           "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),

    # ══════════════════════════════════════════════════════════════════════════
    # CABLE ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("cable_rdl",               "Cable Romanian Deadlift",          "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("cable_good_morning",      "Cable Good Morning",               "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),
    ("cable_split_squat",       "Cable Split Squat",                "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("cable_hip_thrust",        "Cable Hip Thrust",                 "compound","lower",
     ["glutes"],                    ["hamstrings","lower_back"]),
    ("cable_single_leg_rdl",    "Cable Single Leg RDL",             "compound","lower",
     ["hamstrings","glutes"],       ["lower_back","core"]),
    ("cable_sumo_squat",        "Cable Sumo Squat",                 "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("cable_stiff_leg_deadlift","Cable Stiff Leg Deadlift",         "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("cable_reverse_fly",       "Cable Reverse Fly",                "isolation","upper",
     ["rear_delts"],                ["rhomboids","mid_traps"]),
    ("cable_single_arm_fly",    "Cable Single Arm Fly",             "isolation","upper",
     ["chest"],                     ["front_delts"]),
    ("cable_drag_curl",         "Cable Drag Curl",                  "isolation","upper",
     ["biceps"],                    ["brachialis","rear_delts"]),
    ("cable_spider_curl",       "Cable Spider Curl",                "isolation","upper",
     ["biceps"],                    ["brachialis"]),
    ("cable_reverse_curl",      "Cable Reverse Curl",               "isolation","upper",
     ["biceps","forearms"],         ["brachialis"]),
    ("cable_tate_press",        "Cable Tate Press",                 "isolation","upper",
     ["triceps"],                   ["forearms","chest"]),
    ("cable_hip_flexion",       "Cable Hip Flexion",                "isolation","lower",
     ["hip_flexors"],               ["quadriceps"]),
    ("cable_external_rotation", "Cable External Rotation",          "isolation","upper",
     ["rotator_cuff"],              ["rear_delts"]),
    ("cable_internal_rotation", "Cable Internal Rotation",          "isolation","upper",
     ["rotator_cuff"],              ["front_delts"]),
    ("cable_lateral_squat",     "Cable Lateral Squat",              "compound","lower",
     ["glutes","adductors"],        ["quadriceps"]),
    ("cable_tricep_overhead",   "Cable Tricep Overhead Extension",  "isolation","upper",
     ["triceps"],                   ["forearms"]),
    ("cable_low_row_wide_grip", "Cable Low Row Wide Grip",          "compound","upper",
     ["lats","mid_back"],           ["biceps","rear_delts"]),
    ("cable_low_row_narrow",    "Cable Low Row Narrow Grip",        "compound","upper",
     ["lats","teres_major"],        ["biceps"]),
    ("cable_high_row_wide",     "Cable High Row Wide Grip",         "compound","upper",
     ["upper_back","rear_delts"],   ["biceps"]),
    ("cable_neutral_row",       "Cable Neutral Grip Row",           "compound","upper",
     ["back","lats"],               ["biceps"]),
    ("cable_straight_arm_pull", "Cable Straight Arm Pulldown",      "isolation","upper",
     ["lats"],                      ["teres_major","chest"]),

    # ══════════════════════════════════════════════════════════════════════════
    # SMITH MACHINE ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("smith_machine_rdl",       "Smith Machine Romanian Deadlift",  "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("smith_machine_front_squat","Smith Machine Front Squat",       "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),
    ("smith_machine_sumo_squat","Smith Machine Sumo Squat",         "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("smith_machine_split_squat","Smith Machine Split Squat",       "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("smith_machine_bulgarian_split_squat","Smith Machine Bulgarian Split Squat","compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("smith_machine_good_morning","Smith Machine Good Morning",     "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),
    ("smith_machine_lunge",     "Smith Machine Lunge",              "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("smith_machine_reverse_lunge","Smith Machine Reverse Lunge",   "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("smith_machine_close_grip_bench","Smith Machine Close Grip Bench","compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("smith_machine_floor_press","Smith Machine Floor Press",       "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("smith_machine_z_press",   "Smith Machine Z-Press",            "compound","upper",
     ["shoulders"],                 ["triceps","core"]),
    ("smith_machine_upright_row","Smith Machine Upright Row",       "compound","upper",
     ["shoulders","traps"],         ["biceps"]),
    ("smith_machine_bent_over_row","Smith Machine Bent Over Row",   "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("smith_machine_neutral_grip_press","Smith Machine Neutral Grip Press","compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("smith_machine_reverse_grip_bench","Smith Machine Reverse Grip Bench","compound","upper",
     ["upper_chest","biceps"],      ["front_delts"]),

    # ══════════════════════════════════════════════════════════════════════════
    # BENCH PRESS ANGLE / GRIP VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("barbell_bench_15_incline","Barbell Bench Press 15° Incline",  "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("barbell_bench_30_incline","Barbell Bench Press 30° Incline",  "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("barbell_bench_45_incline","Barbell Bench Press 45° Incline",  "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("barbell_bench_60_incline","Barbell Bench Press 60° Incline",  "compound","upper",
     ["chest","front_delts"],       ["triceps"]),
    ("barbell_bench_75_incline","Barbell Bench Press 75° Incline (High Incline)","compound","upper",
     ["front_delts","chest"],       ["triceps"]),
    ("barbell_bench_15_decline","Barbell Bench Press 15° Decline",  "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("barbell_bench_30_decline","Barbell Bench Press 30° Decline",  "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("wide_grip_bench_press",   "Wide Grip Bench Press",            "compound","upper",
     ["chest"],                     ["front_delts","triceps"]),
    ("reverse_grip_bench_press","Reverse Grip Bench Press",         "compound","upper",
     ["upper_chest","biceps"],      ["triceps","front_delts"]),
    ("pause_bench_press",       "Pause Bench Press",                "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("touch_and_go_bench_press","Touch and Go Bench Press",         "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("dumbbell_incline_neutral_press","Dumbbell Incline Neutral Grip Press","compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("dumbbell_decline_neutral_press","Dumbbell Decline Neutral Grip Press","compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("dumbbell_close_grip_press","Dumbbell Close Grip Press",       "compound","upper",
     ["triceps"],                   ["chest","front_delts"]),

    # ══════════════════════════════════════════════════════════════════════════
    # PULL-UP / CHIN-UP VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("close_grip_pull_up",      "Close Grip Pull-Up",               "compound","upper",
     ["lats","biceps"],             ["teres_major"]),
    ("behind_neck_pull_up",     "Behind the Neck Pull-Up",          "compound","upper",
     ["lats","upper_back"],         ["biceps"]),
    ("chest_to_bar_pull_up",    "Chest-to-Bar Pull-Up",             "compound","upper",
     ["lats","upper_back"],         ["biceps","rear_delts"]),
    ("muscle_up",               "Muscle-Up",                        "compound","upper",
     ["lats","chest","triceps"],    ["biceps","shoulders"]),
    ("ring_muscle_up",          "Ring Muscle-Up",                   "compound","upper",
     ["lats","chest","triceps"],    ["biceps","core"]),
    ("ring_pull_up",            "Ring Pull-Up",                     "compound","upper",
     ["lats"],                      ["biceps","teres_major","core"]),
    ("ring_chin_up",            "Ring Chin-Up",                     "compound","upper",
     ["lats","biceps"],             ["teres_major","core"]),
    ("ring_dip",                "Ring Dip",                         "compound","upper",
     ["triceps","chest"],           ["front_delts","core"]),
    ("kipping_pull_up",         "Kipping Pull-Up",                  "compound","full_body",
     ["lats","back"],               ["biceps","shoulders","core"]),
    ("typewriter_pull_up",      "Typewriter Pull-Up",               "compound","upper",
     ["lats","upper_back"],         ["biceps"]),
    ("archer_pull_up",          "Archer Pull-Up",                   "compound","upper",
     ["lats"],                      ["biceps","core"]),
    ("l_sit_pull_up",           "L-Sit Pull-Up",                    "compound","upper",
     ["lats","abs"],                ["biceps","hip_flexors"]),
    ("weighted_chin_up",        "Weighted Chin-Up",                 "compound","upper",
     ["biceps","lats"],             ["teres_major"]),
    ("single_arm_pull_up",      "Single Arm Pull-Up",               "compound","upper",
     ["lats"],                      ["biceps","core"]),

    # ══════════════════════════════════════════════════════════════════════════
    # PUSH-UP VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("deficit_push_up",         "Deficit Push-Up",                  "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("diamond_push_up",         "Diamond Push-Up",                  "compound","upper",
     ["triceps"],                   ["chest","front_delts"]),
    ("archer_push_up",          "Archer Push-Up",                   "compound","upper",
     ["chest"],                     ["triceps","core"]),
    ("pike_push_up",            "Pike Push-Up",                     "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("hindu_push_up",           "Hindu Push-Up",                    "compound","upper",
     ["chest","shoulders"],         ["triceps","back"]),
    ("pseudo_planche_push_up",  "Pseudo Planche Push-Up",           "compound","upper",
     ["chest","front_delts"],       ["triceps","core"]),
    ("wide_grip_push_up",       "Wide Grip Push-Up",                "compound","upper",
     ["chest"],                     ["front_delts","triceps"]),
    ("explosive_push_up",       "Explosive Push-Up / Plyo Push-Up", "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("handstand_push_up",       "Handstand Push-Up",                "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("wall_handstand_push_up",  "Wall Handstand Push-Up",           "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),

    # ══════════════════════════════════════════════════════════════════════════
    # ROW VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("barbell_row_supinated",   "Barbell Row (Supinated/Underhand)","compound","upper",
     ["back","biceps"],             ["rear_delts","lower_back"]),
    ("barbell_row_wide_grip",   "Barbell Row Wide Grip",            "compound","upper",
     ["upper_back","rear_delts"],   ["biceps"]),
    ("barbell_row_close_grip",  "Barbell Row Close Grip",           "compound","upper",
     ["lats","mid_back"],           ["biceps"]),
    ("dumbbell_single_arm_row", "Dumbbell Single Arm Row",          "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("seated_row_wide_grip",    "Seated Row Wide Grip",             "compound","upper",
     ["upper_back","rear_delts"],   ["biceps"]),
    ("seated_row_close_grip",   "Seated Row Close Grip",            "compound","upper",
     ["lats","mid_back"],           ["biceps"]),
    ("seated_row_neutral_grip", "Seated Row Neutral Grip",          "compound","upper",
     ["back","lats"],               ["biceps"]),
    ("trx_row",                 "TRX Row",                          "compound","upper",
     ["back"],                      ["biceps","core"]),
    ("banded_row",              "Banded Row",                       "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("cable_high_pull",         "Cable High Pull",                  "compound","upper",
     ["upper_back","rear_delts"],   ["biceps","traps"]),
    ("snatch_grip_row",         "Snatch Grip Row",                  "compound","upper",
     ["upper_back","rear_delts"],   ["traps","biceps"]),
    ("helms_row",               "Helms Row",                        "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("machine_high_row",        "Machine High Row",                 "compound","upper",
     ["upper_back","lats"],         ["biceps","rear_delts"]),
    ("machine_low_row",         "Machine Low Row",                  "compound","upper",
     ["lats","mid_back"],           ["biceps","teres_major"]),
    ("machine_neutral_row",     "Machine Neutral Grip Row",         "compound","upper",
     ["back","lats"],               ["biceps"]),

    # ══════════════════════════════════════════════════════════════════════════
    # SQUAT VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("barbell_overhead_squat",  "Barbell Overhead Squat",           "compound","full_body",
     ["quadriceps"],                ["glutes","shoulders","core","hamstrings"]),
    ("cossack_squat",           "Cossack Squat",                    "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("hatfield_squat",          "Hatfield Squat",                   "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","core"]),
    ("anderson_squat",          "Anderson Squat (From Pins)",       "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("frankenstein_squat",      "Frankenstein Squat",               "compound","lower",
     ["quadriceps"],                ["glutes","core"]),
    ("spanish_squat",           "Spanish Squat",                    "compound","lower",
     ["quadriceps"],                ["glutes","calves"]),
    ("quarter_squat",           "Quarter Squat / Partial Squat",    "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),
    ("tempo_squat",             "Tempo Squat",                      "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("1.5_rep_squat",           "1.5-Rep Squat",                    "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("heel_elevated_front_squat","Heel Elevated Front Squat",       "compound","lower",
     ["quadriceps"],                ["glutes","calves"]),
    ("wide_stance_squat",       "Wide Stance Barbell Squat",        "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("narrow_stance_squat",     "Narrow Stance Barbell Squat",      "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),
    ("bodyweight_squat",        "Bodyweight Squat",                 "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("jump_squat",              "Jump Squat",                       "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("wall_sit",                "Wall Sit",                         "isolation","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),
    ("banded_squat",            "Banded Squat",                     "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","abductors"]),

    # ══════════════════════════════════════════════════════════════════════════
    # DEADLIFT VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("snatch_grip_deadlift",    "Snatch Grip Deadlift",             "compound","lower",
     ["hamstrings","glutes","back"],["traps","upper_back","forearms"]),
    ("jefferson_deadlift",      "Jefferson Deadlift",               "compound","lower",
     ["glutes","adductors","hamstrings"],["back","core"]),
    ("sumo_block_pull",         "Sumo Block Pull",                  "compound","lower",
     ["hamstrings","glutes"],       ["back","traps"]),
    ("sumo_deficit_deadlift",   "Sumo Deficit Deadlift",            "compound","lower",
     ["hamstrings","glutes","adductors"],["back","traps"]),
    ("block_pull",              "Block Pull",                       "compound","lower",
     ["hamstrings","glutes","back"],["traps","forearms"]),
    ("touch_and_go_deadlift",   "Touch and Go Deadlift",            "compound","lower",
     ["hamstrings","glutes","back"],["traps","quadriceps"]),
    ("pause_rdl",               "Pause Romanian Deadlift",          "compound","lower",
     ["hamstrings"],                ["glutes","lower_back"]),
    ("banded_deadlift",         "Banded Deadlift",                  "compound","lower",
     ["hamstrings","glutes","back"],["traps","quadriceps"]),
    ("zercher_deadlift",        "Zercher Deadlift",                 "compound","full_body",
     ["hamstrings","glutes","back"],["biceps","upper_back","quadriceps"]),
    ("suitcase_deadlift",       "Suitcase Deadlift",                "compound","lower",
     ["hamstrings","glutes","back"],["core","obliques","traps"]),
    ("dumbbell_deadlift",       "Dumbbell Deadlift",                "compound","lower",
     ["hamstrings","glutes","back"],["traps","forearms"]),

    # ══════════════════════════════════════════════════════════════════════════
    # GOOD MORNING VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("seated_good_morning",     "Seated Good Morning",              "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),
    ("wide_stance_good_morning","Wide Stance Good Morning",         "compound","lower",
     ["hamstrings","glutes"],       ["lower_back","adductors"]),
    ("banded_good_morning",     "Banded Good Morning",              "compound","lower",
     ["hamstrings"],                ["lower_back","glutes"]),

    # ══════════════════════════════════════════════════════════════════════════
    # OVERHEAD PRESS VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("seated_dumbbell_ohp",     "Seated Dumbbell Overhead Press",   "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("seated_arnold_press",     "Seated Arnold Press",              "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("behind_neck_press",       "Behind the Neck Press",            "compound","upper",
     ["shoulders","upper_back"],    ["triceps"]),
    ("dumbbell_push_press",     "Dumbbell Push Press",              "compound","upper",
     ["shoulders","quadriceps"],    ["triceps","core"]),
    ("landmine_push_press",     "Landmine Push Press",              "compound","upper",
     ["shoulders","quadriceps"],    ["triceps","core"]),
    ("single_arm_push_press",   "Single Arm Push Press",            "compound","upper",
     ["shoulders","quadriceps"],    ["triceps","core"]),
    ("banded_overhead_press",   "Banded Overhead Press",            "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("viking_press_single_arm", "Viking Press Single Arm",          "compound","upper",
     ["shoulders"],                 ["triceps","upper_chest"]),
    ("plate_press",             "Plate Press Overhead",             "compound","upper",
     ["shoulders"],                 ["triceps","chest"]),
    ("kettlebell_jerk",         "Kettlebell Jerk",                  "compound","full_body",
     ["shoulders","quadriceps"],    ["triceps","core","glutes"]),

    # ══════════════════════════════════════════════════════════════════════════
    # CORE ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("copenhagen_plank",        "Copenhagen Plank",                 "isolation","lower",
     ["adductors","obliques"],      ["core","glutes"]),
    ("hollow_hold",             "Hollow Hold",                      "isolation","upper",
     ["abs","core"],                ["hip_flexors"]),
    ("arch_hold",               "Arch Hold",                        "isolation","lower",
     ["erectors","glutes"],         ["hamstrings"]),
    ("dragon_flag_negative",    "Dragon Flag Negative",             "isolation","upper",
     ["abs","core"],                ["hip_flexors","chest"]),
    ("cable_woodchop",          "Cable Woodchop",                   "compound","upper",
     ["obliques","core"],           ["shoulders","hip_flexors"]),
    ("ghr_sit_up",              "GHR Sit-Up",                       "isolation","upper",
     ["abs","hip_flexors"],         ["erectors"]),
    ("ab_roller",               "Ab Roller",                        "isolation","upper",
     ["abs","core"],                ["shoulders","lats","hip_flexors"]),
    ("stability_ball_rollout",  "Stability Ball Rollout",           "isolation","upper",
     ["abs","core"],                ["shoulders","lats"]),
    ("suitcase_carry",          "Suitcase Carry",                   "compound","full_body",
     ["core","obliques"],           ["traps","forearms","glutes"]),
    ("overhead_carry",          "Overhead Carry",                   "compound","full_body",
     ["shoulders","core"],          ["traps","triceps"]),
    ("zercher_carry",           "Zercher Carry",                    "compound","full_body",
     ["core","back"],               ["biceps","glutes","quadriceps"]),
    ("yoke_carry",              "Yoke Carry",                       "compound","full_body",
     ["traps","core"],              ["glutes","quadriceps","calves"]),
    ("sandbag_carry",           "Sandbag Carry",                    "compound","full_body",
     ["core","back"],               ["glutes","shoulders","forearms"]),
    ("stir_the_pot",            "Stir the Pot (Stability Ball)",    "isolation","upper",
     ["abs","obliques","core"],     ["shoulders"]),

    # ══════════════════════════════════════════════════════════════════════════
    # ROTATOR CUFF / SHOULDER HEALTH
    # ══════════════════════════════════════════════════════════════════════════
    ("external_rotation",       "External Rotation (Dumbbell)",     "isolation","upper",
     ["rotator_cuff"],              ["rear_delts"]),
    ("internal_rotation",       "Internal Rotation (Dumbbell)",     "isolation","upper",
     ["rotator_cuff"],              ["front_delts"]),
    ("sleeper_stretch",         "Sleeper Stretch",                  "isolation","upper",
     ["rotator_cuff"],              []),
    ("band_external_rotation",  "Band External Rotation",           "isolation","upper",
     ["rotator_cuff"],              ["rear_delts"]),
    ("band_internal_rotation",  "Band Internal Rotation",           "isolation","upper",
     ["rotator_cuff"],              ["front_delts"]),
    ("l_fly",                   "L-Fly / Side Lying External Rotation","isolation","upper",
     ["rotator_cuff"],              ["rear_delts"]),
    ("cuban_press",             "Cuban Press",                      "compound","upper",
     ["rotator_cuff","shoulders"],  ["rear_delts","traps"]),
    ("powell_raise",            "Powell Raise",                     "isolation","upper",
     ["rear_delts"],                ["rotator_cuff"]),

    # ══════════════════════════════════════════════════════════════════════════
    # LUNGE VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("barbell_walking_lunge",   "Barbell Walking Lunge",            "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),
    ("barbell_reverse_lunge",   "Barbell Reverse Lunge",            "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("barbell_curtsy_lunge",    "Barbell Curtsy Lunge",             "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("barbell_lateral_lunge",   "Barbell Lateral Lunge",            "compound","lower",
     ["glutes","adductors"],        ["quadriceps","hamstrings"]),
    ("barbell_deficit_lunge",   "Barbell Deficit Lunge",            "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("cable_lunge",             "Cable Lunge",                      "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","core"]),
    ("smith_machine_forward_lunge","Smith Machine Forward Lunge",   "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings"]),
    ("overhead_lunge",          "Overhead Lunge",                   "compound","lower",
     ["quadriceps","glutes"],       ["shoulders","core","hamstrings"]),
    ("jump_lunge",              "Jump Lunge",                       "compound","lower",
     ["quadriceps","glutes"],       ["hamstrings","calves"]),

    # ══════════════════════════════════════════════════════════════════════════
    # HIP HINGE VARIATIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("45_degree_hyperextension","45-Degree Hyperextension",         "compound","lower",
     ["erectors","glutes"],         ["hamstrings"]),
    ("back_extension_weighted", "Weighted Back Extension",          "compound","lower",
     ["erectors","lower_back"],     ["glutes","hamstrings"]),
    ("hip_hinge_wall_drill",    "Hip Hinge Wall Drill",             "compound","lower",
     ["hamstrings","glutes"],       ["lower_back"]),
    ("dumbbell_pull_through",   "Dumbbell Pull Through",            "compound","lower",
     ["glutes","hamstrings"],       ["lower_back"]),
    ("cable_pull_through_single","Single Leg Cable Pull Through",   "compound","lower",
     ["glutes","hamstrings"],       ["lower_back","core"]),

    # ══════════════════════════════════════════════════════════════════════════
    # CALF / LOWER LEG ADDITIONS
    # ══════════════════════════════════════════════════════════════════════════
    ("barbell_calf_raise",      "Barbell Standing Calf Raise",      "isolation","lower",
     ["calves"],                    ["soleus","tibialis"]),
    ("dumbbell_calf_raise",     "Dumbbell Calf Raise",              "isolation","lower",
     ["calves"],                    ["soleus","tibialis"]),
    ("seated_machine_calf_raise","Seated Machine Calf Raise",       "isolation","lower",
     ["soleus"],                    ["gastrocnemius"]),
    ("calf_raise_on_leg_press", "Calf Raise on Leg Press",          "isolation","lower",
     ["calves"],                    ["soleus"]),
    ("single_leg_donkey_calf_raise","Single Leg Donkey Calf Raise", "isolation","lower",
     ["calves"],                    ["soleus"]),
    ("tibialis_anterior_raise", "Tibialis Anterior Raise",          "isolation","lower",
     ["tibialis_anterior"],         []),
    ("banded_dorsiflexion",     "Banded Dorsiflexion",              "isolation","lower",
     ["tibialis_anterior"],         []),
    ("heel_drop",               "Heel Drop (Eccentric Calf)",       "isolation","lower",
     ["calves"],                    ["achilles"]),

    # ══════════════════════════════════════════════════════════════════════════
    # ISOMETRIC / SPECIALTY
    # ══════════════════════════════════════════════════════════════════════════
    ("isometric_squat",         "Isometric Squat Hold",             "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),
    ("isometric_bench_press",   "Isometric Bench Press",            "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("isometric_row",           "Isometric Row",                    "compound","upper",
     ["back"],                      ["biceps","rear_delts"]),
    ("pause_bench_incline",     "Pause Incline Bench Press",        "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("pause_squat_high_bar",    "Pause High Bar Squat",             "compound","lower",
     ["quadriceps"],                ["glutes","hamstrings"]),
    ("tempo_bench_press",       "Tempo Bench Press",                "compound","upper",
     ["chest"],                     ["triceps","front_delts"]),
    ("tempo_deadlift",          "Tempo Deadlift",                   "compound","lower",
     ["hamstrings","glutes","back"],["traps","quadriceps"]),
]


def run():
    conn = sqlite3.connect(str(DB_PATH))
    cur = conn.cursor()

    # ── STEP 1: patch secondary muscles ──────────────────────────────────────
    patched = 0
    for name, muscles in SECONDARY_PATCHES.items():
        cur.execute(
            "SELECT id FROM exercises WHERE name = ?", (name,)
        )
        row = cur.fetchone()
        if row:
            cur.execute(
                "UPDATE exercises SET secondary_muscles = ? WHERE name = ?",
                (json.dumps(muscles), name),
            )
            patched += 1
        else:
            print(f"  [PATCH SKIP] not found: {name}")

    print(f"✓ Patched secondary muscles on {patched} exercises")

    # ── STEP 2: add new exercises ─────────────────────────────────────────────
    added = 0
    skipped = 0
    for row in NEW_EXERCISES:
        name, display_name, movement_type, body_region, primary, secondary = row
        cur.execute("SELECT id FROM exercises WHERE name = ?", (name,))
        if cur.fetchone():
            skipped += 1
            continue
        cur.execute(
            """INSERT INTO exercises
               (name, display_name, movement_type, body_region,
                primary_muscles, secondary_muscles,
                created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))""",
            (
                name,
                display_name,
                movement_type,
                body_region,
                json.dumps(primary),
                json.dumps(secondary),
            ),
        )
        added += 1

    conn.commit()
    conn.close()

    print(f"✓ Added {added} new exercises  ({skipped} already existed)")
    print(f"\n🎉 Done! Total new DB exercises ≈ 326 + {added}")


if __name__ == "__main__":
    run()
